Fix product custom attribute value with semicolon breaks sync.
woocommerce/facebook-for-woocommerce pull request #2195
Opened 2022-04-26 10:11 UTC by message-dimke

When variable product has custom attribute with semicolon in its values, product sync for Facebook fails.

### Changes proposed in this Pull Request:

Introduce a filter for custom attribute value to remove semicolon and allow to redefine such a behaviour.

Closes #2063.

### Detailed test instructions:

1. Create variable product with at least one custom attribute which has value with semicolon in it.

<img width="1223" alt="Edit_product_“V-Neck_T-Shirt_UTF8_Compatible”_‹_WordPress-Facebook_—_WordPress" src="https://user-images.githubusercontent.com/9010963/165276730-8f53542c-c85f-4131-9ec9-9de5244ca965.png">

2. Sync product to Facebook and see product was not synced, but WooCommerce > Status > Logs has Facebook-for-woocommerce log with records about sync failure.

<img width="1524" alt="Cursor_and_WooCommerce_status_‹_WordPress-Facebook_—_WordPress" src="https://user-images.githubusercontent.com/9010963/165276915-aeec8cca-5cb9-425c-9fc1-94d3af3598d9.png">

3. Pull the new code and repeat the procedure. You should now see the product appear to Facebook with no semicolon in attribute value and no errors in corresponding logs appear.

<img width="1523" alt="WooCommerce_status_‹_WordPress-Facebook_—_WordPress" src="https://user-images.githubusercontent.com/9010963/165277153-be728305-250d-4d75-8e69-760059467403.png">

<img width="1066" alt="_4__Facebook" src="https://user-images.githubusercontent.com/9010963/165277189-6cdba312-cfbc-4a21-a060-5dcd08268347.png">

### Changelog entry

> Fix - remove semicolon from custom attribute value

2022-04-26 12:26 UTC, rawdreeg requested changes
Thanks for the fix @message-dimke.

The logic works well and fixes the error.  However, the symbol replaced is a colon (:) and not a semicolon (;). Maybe we should rename the filter to  `facebook_for_woocommerce_variant_attribute_colon_replacement`-- although that [reads a bit funny](https://en.wikipedia.org/wiki/Colectomy) 😆 .

2022-04-26 16:22 UTC, message-dimke commented
Hey, @rawdreeg. I removed the filter for colon since colon can be removed by comma filter as well so there is no need in an extra filter for that character. Instead I forced removing , and : characters from the value before the function return statement since it possible to overwrite , with , or : with :, but we still must make sure those characters are replaced before Facebook sync.

2022-04-27 08:11 UTC, rawdreeg approved these changes
🚀  LGTM!

2022-04-27 15:44 UTC, merged

2022-10-20 19:15 UTC, johndcoy commented
The filter should include `attribute_name` as well. It currently only filters `attribute_value`

2022-10-20 19:16 UTC, johndcoy commented
@rawdreeg @message-dimke The filter should include `attribute_name` as well. It currently only filters `attribute_value`