Syncs product with name in ALL CAPS and displays warning
woocommerce/facebook-for-woocommerce pull request #2589
Opened 2023-07-20 10:17 UTC by krutidugade

### Changes proposed in this Pull Request:

Closes #2582.

_Replace this with a good description of your changes & reasoning._

- [ ] Do the changed files pass `phpcs` checks? Please remove `phpcs:ignore` comments in changed files and fix any issues, or delete if not practical.

### Screenshots:

### Detailed test instructions:

1. 
2. 
3. 

### Additional details:

### Changelog entry

>

2023-07-25 04:53 UTC, rawdreeg approved these changes
Thanks @krutidugade . LGTM! 👍🏾

2023-07-25 08:17 UTC, budzanowski commented
Two things.

First. I think that the sentence that you propose is a bit vague. `may have issues` does not tell a lot to the merchant about the nature of the product.

Please consider a variant of:
`Product title in all capital letters can lead to the server rejecting the product. To ensure successful product synchronization, please convert the product title to a sentence case.`

Second.
Why show the sentence in case the product got synced? :) If we have the fb_product_id we should be good.

2023-07-25 08:17 UTC, budzanowski commented
One more thing. Have you tested how it looks for a variation product with multiple variants?

2023-07-25 08:18 UTC, budzanowski requested changes
Please check the comments and adjust.

2023-07-25 19:35 UTC, krutidugade commented
>Please consider a variant of:
`Product title in all capital letters can lead to the server rejecting the product. To ensure successful product synchronization, please convert the product title to a sentence case.`

Sure, this looks neat.

>Why show the sentence in case the product got synced? :) If we have the fb_product_id we should be good.

Understood. I was under the impression that we want to sync the product and show the notice irrespective of the product being synced.

>One more thing. Have you tested how it looks for a variation product with multiple variants?

No, I missed this part. The Variant IDs aren't generated. I'll look into this.

2023-07-25 19:58 UTC, budzanowski commented
> Understood. I was under the impression that we want to sync the product and show the notice irrespective of the product being synced.

This is my question basically. What should we do? I think that your proposal is the best option. I just want to be sure that we have thought about everything. Don't hesitate to question my thoughts and statements in case you feel or know that they are wrong.

2023-07-26 15:37 UTC, krutidugade commented
>This is my question basically. What should we do? I think that your proposal is the best option. I just want to be sure that we have thought about everything. Don't hesitate to question my thoughts and statements in case you feel or know that they are wrong.

Noted. I do think it is best we show the notice irrespective of the product being synced. In the following screenshot, we can see one variant isn't synced so the product wasn't synced properly.

<img width="298" alt="Screenshot 2023-07-26 at 4 25 58 PM" src="https://github.com/woocommerce/facebook-for-woocommerce/assets/33723519/fadef6e6-49e1-487d-929c-ea4fe83d5997">


I have updated the code. The notice can be seen after FB and variant IDs.

<img width="299" alt="Screenshot 2023-07-26 at 4 21 26 PM" src="https://github.com/woocommerce/facebook-for-woocommerce/assets/33723519/f7257d90-529d-4344-a88f-3f5cb1b28f53">
<img width="305" alt="Screenshot 2023-07-26 at 4 33 00 PM" src="https://github.com/woocommerce/facebook-for-woocommerce/assets/33723519/9036690f-cca4-45a0-8492-b97c0fae9f9b">

2023-08-01 08:13 UTC, budzanowski approved these changes

2023-08-01 13:09 UTC, merged