Fixed AddToCart duplication when other plugins clone cart
woocommerce/facebook-for-woocommerce pull request #2631
Opened 2023-09-16 18:26 UTC by StyleT

### Changes proposed in this Pull Request:

Other plugins often clone Woocommerce cart to do various "on the fly" calculations and now this causes duplication of the AddToCart server events.

This fixes it once and forever ;)

### Screenshots:
How it looks before fix:
<img width="2012" alt="Screenshot 2023-09-16 at 2 19 38 PM" src="https://github.com/woocommerce/facebook-for-woocommerce/assets/1125900/739c6ddf-d764-4125-a836-ff1406bb91b1">

### Detailed test instructions:
#### How to reproduce in tests
```
$cart = clone WC()->cart;
$cart->add_to_cart( $product_id, $qty, $variation_id, $variation )
```

#### Real-life test
Install this plugin and `woo-stripe-payment` as an example. Observe the following stack traces:

```
2023-09-16T17:51:06+00:00 DEBUG AddToCart: #0 /wp-includes/class-wp-hook.php(312): WC_Facebookcommerce_EventsTracker->inject_add_to_cart_event()
#1 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-content/plugins/woocommerce/includes/class-wc-cart.php(1279): do_action()
#4 /wp-content/plugins/woo-stripe-payment/includes/controllers/class-wc-stripe-controller-cart.php(275): WC_Cart->add_to_cart()
#5 /wp-includes/rest-api/class-wp-rest-server.php(1188): WC_Stripe_Controller_Cart->cart_calculation()
#6 /wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request()
#7 /wp-includes/rest-api/class-wp-rest-server.php(447): WP_REST_Server->dispatch()
#8 /wp-includes/rest-api.php(418): WP_REST_Server->serve_request()
#9 /wp-content/plugins/woo-stripe-payment/includes/class-wc-stripe-rest-api.php(159): rest_api_loaded()
#10 /wp-includes/class-wp-hook.php(310): WC_Stripe_Rest_API->process_frontend_request()
#11 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#12 /wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#14 /wp-includes/class-wp-hook.php(310): WC_AJAX::do_wc_ajax()
#15 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#16 /wp-includes/plugin.php(517): WP_Hook->do_action()
#17 /wp-includes/template-loader.php(13): do_action()
#18 /wp-blog-header.php(19): require_once('/var/www/html/u...')
#19 /index.php(17): require('/var/www/html/u...')
#20 {main}
```

2023-09-18 06:22 UTC, ibndawood commented
Thank you, @StyleT, for your contribution. We'll have this PR reviewed by our team as soon as possible.

2023-09-28 13:10 UTC, rawdreeg requested changes
Code is good, and thanks for your contribution. Just a coding style related issue to be fixed before we can merge this.

2023-09-28 13:10 UTC, rawdreeg commented on facebook-commerce-events-tracker.php
> +			if (!isset($cart->cart_contents[ $cart_item_key ])) {
```suggestion
			if ( ! isset( $cart->cart_contents[ $cart_item_key ] ) ) {
```

2023-09-28 13:12 UTC, rawdreeg commented on facebook-commerce-events-tracker.php
> +			if (!isset($cart->cart_contents[ $cart_item_key ])) {
also let's add a check to make sure we can call cart_contents on $cart

2023-10-02 11:52 UTC, rawdreeg commented
Hi @StyleT,

I have dropped a few review comments. Let us know if you have any questions.

Thanks.
R

2023-10-04 08:39 UTC, rawdreeg approved these changes

2023-10-04 08:57 UTC, merged