Add video syncs to fbproduct
woocommerce/facebook-for-woocommerce pull request #2692
Opened 2024-02-19 10:54 UTC by rahulraina7

### Changes proposed in this Pull Request:

Along with syncing images, I would also like to sync videos to the facebook catalog.
Although woo-commerce natively doesn't support product videos, but you can insert/attach a product video in the description.

Currently the video syncing is only supported by [batch-api](https://developers.facebook.com/docs/marketing-api/reference/product-catalog/items_batch/) / feed upload so this has to be merged after https://github.com/woocommerce/facebook-for-woocommerce/pull/2654

This pull requests adds the following
* Extracts video links from product description (no native support for video / video-gallerys)

### 2 sets of flows are affected
* items batch and feed support flow support

### Tests
* Integration tests are updated and CI passing in forked repo - https://github.com/rahulraina7/facebook-for-woocommerce/actions/runs/6556265345
* **E2E Tests**
   - Single Product Update
       * Go to individual product. Upload a video in description
       * Click Publish->Update
       * Outcome : Video Synced to facebook
   - Batch API Update
      * Disconnect from facebook
      * Connect back and create a new catalog
      * Products are synced with batch API flow
      * Outcomes : New catalog created on facebook, with Videos synced at product level

2024-02-19 10:56 UTC, rahulraina7 commented
cc - @budzanowski , @ibndawood I have opened this PR directly in this branch

2024-02-21 15:08 UTC, ibndawood requested changes
Hello @rahulraina7, thank you for the PR. I followed the test instructions. However, I am not able to confirm this behaviour:

> Outcome : Video Synced to facebook

Here is the request log:

```
method: POST
uri: https://graph.facebook.com/v17.0/1476533009578377/items_batch
user-agent: Facebook-for-WooCommerce/3.1.10 (WooCommerce/8.6.1; WordPress/6.4.3)
body: {"allow_upsert":true,"requests":[{"method":"UPDATE","data":{"title":"Woo Book new","description":"Woo Book new","image_link":"https:\/\/fbwctesting.mystagingwebsite.com\/wp-content\/uploads\/2022\/09\/album-1.jpg","additional_image_link":[],"link":"https:\/\/fbwctesting.mystagingwebsite.com\/product\/woo-book\/","product_type":"Uncategorized","brand":"FBWC","price":"101 USD","availability":"in stock","visibility":"published","sale_price_effective_date":"","sale_price":"","video":[{"url":"https:\/\/fbwctesting.mystagingwebsite.com\/wp-content\/uploads\/2023\/12\/SampleVideo_1280x720_5mb.mp4"}],"item_group_id":"wc_post_id_253","condition":"new","id":"wc_post_id_253"}}],"item_type":"PRODUCT_ITEM"}
duration: 1.91994s
```

The response was `200 OK`. I checked the product in the commerce manager but I couldn't find the video URL attribute. Screenshot below:

![image](https://github.com/woocommerce/facebook-for-woocommerce/assets/179533/a080e73e-7884-4c3f-bc72-c21011c49f05)

I clicked the "Show more attributes" button but there was no `Videos` attribute at all. Can you please let me know if I've missed anything?

2024-02-21 16:38 UTC, rahulraina7 commented
> Hello @rahulraina7, thank you for the PR. I followed the test instructions. However, I am not able to confirm this behaviour:
> 
> > Outcome : Video Synced to facebook
> 
> Here is the request log:
> 
> ```
> method: POST
> uri: https://graph.facebook.com/v17.0/1476533009578377/items_batch
> user-agent: Facebook-for-WooCommerce/3.1.10 (WooCommerce/8.6.1; WordPress/6.4.3)
> body: {"allow_upsert":true,"requests":[{"method":"UPDATE","data":{"title":"Woo Book new","description":"Woo Book new","image_link":"https:\/\/fbwctesting.mystagingwebsite.com\/wp-content\/uploads\/2022\/09\/album-1.jpg","additional_image_link":[],"link":"https:\/\/fbwctesting.mystagingwebsite.com\/product\/woo-book\/","product_type":"Uncategorized","brand":"FBWC","price":"101 USD","availability":"in stock","visibility":"published","sale_price_effective_date":"","sale_price":"","video":[{"url":"https:\/\/fbwctesting.mystagingwebsite.com\/wp-content\/uploads\/2023\/12\/SampleVideo_1280x720_5mb.mp4"}],"item_group_id":"wc_post_id_253","condition":"new","id":"wc_post_id_253"}}],"item_type":"PRODUCT_ITEM"}
> duration: 1.91994s
> ```
> 
> The response was `200 OK`. I checked the product in the commerce manager but I couldn't find the video URL attribute. Screenshot below:
> 
> ![image](https://private-user-images.githubusercontent.com/179533/306671554-a080e73e-7884-4c3f-bc72-c21011c49f05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzM3MTUsIm5iZiI6MTcwODUzMzQxNSwicGF0aCI6Ii8xNzk1MzMvMzA2NjcxNTU0LWEwODBlNzNlLTc4ODQtNGMzZi1iYzcyLWMyMTAxMWM0OWYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxNjM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTUyNDcwZTcyN2JkYmZjZmE4Yjg4NjRkMDQ2MTUyMzhjMzMyYTFmNzZhODMwM2M0NDgxNzFlYmU5NzIzZDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NZu5Yt8tsZM4lAiFofp4qq0SM8MJIdvLQCW7Pm0AtSY)
> 
> I clicked the "Show more attributes" button but there was no `Videos` attribute at all. Can you please let me know if I've missed anything?

No I don't think so you are missing something. Meta only downloads the videos usually when its needed example - ad impressions. So it may not immediately appear in commerce manager for preview. Let me try and whitelist.

2024-02-22 06:26 UTC, ibndawood commented on includes/fbproduct.php
> +			$url = $video->guid;
```suggestion
			$url = wp_get_attachment_url( $video->ID );
```

`guid` is not reliable. Please use the WordPress function `wp_get_attachment_url` which will internally use guid as [a fallback](https://developer.wordpress.org/reference/functions/wp_get_attachment_url/#source).

2024-02-22 06:50 UTC, ibndawood approved these changes
Thank you, @rahulraina7, for your clarifications. I confirm that I can see the video in the commerce manager.

![image](https://github.com/woocommerce/facebook-for-woocommerce/assets/179533/71dc25ef-5f53-4f01-8738-b65fe6959f75)

The changes test as expected. I reviewed the code and added one modification, which is to use `wp_get_attachment_url` instead of the `guid` property, which is unreliable.

Also, I'd like to bring to your notice the limitation of `get_attached_media`. The function will only return an array for the first post attached. Here is a[ detailed explanation](https://developer.wordpress.org/reference/functions/get_attached_media/#comment-2771) about this behaviour. Please be aware of this limitation.

I've approved the PR as the changes work as expected.

2024-02-22 08:13 UTC, merged